test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,34 +68,34 @@ jobs:
           paths: [backend/node_modules]
           key: backend-build
 
-  test-frontend:
-    docker:
+#  test-frontend:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
                 
-  test-backend:
-    docker:
+#  test-backend:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
             
-  scan-frontend:
-    docker:
+#  scan-frontend:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
 
-  scan-backend:
-    docker:
+#  scan-backend:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
@@ -160,82 +160,82 @@ jobs:
             exit 1
       # Here's where you will add some code to rollback on failure      
 
-  run-migrations:
-    docker:
+#  run-migrations:
+#    docker:
       # Docker image here that supports NodeJS
-    steps:
+#    steps:
       # Checkout code from git
-      - run:
-          name: Run migrations
-          command: |
+#      - run:
+#          name: Run migrations
+#          command: |
             # Your code here
-            exit 1
-      - run:
-          name: Send migration results to memstash
-          command: |
-            # Your code here
-            exit 1
+#            exit 1
+#      - run:
+#          name: Send migration results to memstash
+#          command: |
+#            # Your code here
+#            exit 1
      # Here's where you will add some code to rollback on failure      
 
-  deploy-frontend:
-    docker:
-      # Docker image here that supports AWS CLI
-    steps:
+#  deploy-frontend:
+#    docker:
+#      # Docker image here that supports AWS CLI
+#    steps:
       # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
+#      - run:
+#          name: Install dependencies
+#          command: |
             # your code here
-      - run:
-          name: Get backend url
-          command: |
+#      - run:
+#          name: Get backend url
+#          command: |
             # your code here
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-      - run:
-          name: Deploy frontend objects
-          command: |
+#            export API_URL="http://${BACKEND_IP}:3030"
+#            echo "${API_URL}"
+#      - run:
+#          name: Deploy frontend objects
+#          command: |
             # your code here
       # Here's where you will add some code to rollback on failure      
                     
-  deploy-backend:
-    docker:
-      # Docker image here that supports Ansible
-    steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-      - run:
-          name: Deploy backend
-          command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+#  deploy-backend:
+#    docker:
+#      # Docker image here that supports Ansible
+#    steps:
+#      # Checkout code from git
+#      # Add ssh keys with fingerprint
+#      # attach workspace
+#      - run:
+#          name: Install dependencies
+#          command: |
+#            # your code here
+#      - run:
+ #         name: Deploy backend
+#          command: |
+ #           # your code here
+#      # Here's where you will add some code to rollback on failure  
 
-  smoke-test:
-    docker:
-      # Lightweight Docker image 
-    steps:
-      # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-      - run:
-          name: Backend smoke test.
-          command: |
-            # your code here
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here
+ # smoke-test:
+ #   docker:
+ #     # Lightweight Docker image 
+ #   steps:
+ #     # Checkout code from git
+ #     - run:
+ #         name: Install dependencies
+ #         command: |
+ #           # your code here
+ #     - run:
+ #         name: Get backend url
+ #         command: |
+ #           # your code here
+ #     - run:
+ #         name: Backend smoke test.
+ #         command: |
+ #           # your code here
+ #     - run:
+ #         name: Frontend smoke test.
+ #         command: |
+ #           # your code here
       # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
